
SELECT 
	 CL_UID 
	,CL_Lang_DE 
	-- ,CL_Lang_FR 
	-- ,CL_Lang_IT 
	-- ,CL_Lang_EN 
	-- ,_TCL_UID
FROM T_CL_Checklist 
WHERE (1=1) 
-- AND CL_Status = 1 
-- AND CL_UID = '44D8AC52-E9DB-4459-B001-A6C825022EF3'
AND CL_Lang_DE = 'Meine Liste' 
ORDER BY CL_Sort, CL_Lang_DE 

-- UPDATE T_CL_Checklist SET CL_Status = 1 WHERE CL_UID = '44D8AC52-E9DB-4459-B001-A6C825022EF3'

SELECT * FROM T_CL_ZO_Table	
WHERE (1=1) 
-- AND ZOCLTT_CL_UID = '44D8AC52-E9DB-4459-B001-A6C825022EF3' -- Generalagenturen/Verkaufsstellen CL_UID 
AND ZOCLTT_CL_UID = 'F84CDF05-6060-47AF-801A-AF4FE4603A40' -- Meine Liste CL_UID 
AND ZOCLTT_Status = 1
ORDER BY ZOCLTT_Sort 

SELECT * FROM [T_CL_ZO_Header] -- on [ZOCLTH_ZOCLTT_UID] = [ZOCLTT_UID] and [ZOCLTH_Status] = 1
WHERE ZOCLTH_ZOCLTT_UID = 'D3E15350-BA29-4D68-8410-16F930C2F590' and [ZOCLTH_Status] = 1

-- left join [T_CL_ZO_Label] on [ZOCLLA_ZOCLTH_UID] = [ZOCLTH_UID] and [ZOCLLA_Status] = 1
SELECT * FROM T_CL_ZO_Label WHERE [ZOCLLA_ZOCLTH_UID] = '48F91396-649F-4F5A-8379-3E76C5C8AFBB' 


-- Wozu ? 
SELECT * FROM T_ZO_CL_Checklist	
WHERE ZO_CL_CL_UID = 'F84CDF05-6060-47AF-801A-AF4FE4603A40'


SELECT 
     ZO_CLV_UID 
	,ZO_CLV_Value 
	--,ZO_CLV_ZOCLTB_UID 
	--,ZO_CLV_ZOCLCB_UID 
	--,ZO_CLV_ZOCLTA_UID
FROM T_ZO_CL_Checklist_Values 
LEFT JOIN T_CL_ZO_CheckBox ON T_CL_ZO_CheckBox.ZOCLCB_UID = T_ZO_CL_Checklist_Values.ZO_CLV_ZOCLCB_UID
LEFT JOIN T_CL_ZO_DropDown ON T_CL_ZO_DropDown.ZOCLDD_UID = T_ZO_CL_Checklist_Values .ZO_CLV_ZOCLDD_UID 
LEFT JOIN T_CL_ZO_TextArea ON T_CL_ZO_TextArea.ZOCLTA_UID = T_ZO_CL_Checklist_Values.ZO_CLV_ZOCLTA_UID 
LEFT JOIN T_CL_ZO_TextBox ON T_CL_ZO_TextBox.ZOCLTB_UID = T_ZO_CL_Checklist_Values.ZO_CLV_ZOCLTB_UID 
LEFT JOIN T_ZO_CL_Checklist ON T_ZO_CL_Checklist.ZO_CL_UID = T_ZO_CL_Checklist_Values.ZO_CLV_ZO_CL_UID 
WHERE ZO_CLV_Status = 1 
AND ZO_CLV_ZO_CL_UID = 'F84CDF05-6060-47AF-801A-AF4FE4603A40' 
