
SELECT * FROM V_DELDATA_ForeignKeyRelations 
WHERE 'T_CL_Checklist' IN (FK_TABLE_NAME, REFERENCED_TABLE_NAME) 

SELECT * FROM V_DELDATA_ForeignKeyRelations 
WHERE 'T_ZO_CL_Checklist' IN (FK_TABLE_NAME, REFERENCED_TABLE_NAME) 



SELECT * FROM V_DELDATA_ForeignKeyRelations 
WHERE 'T_CL_ZO_Table' IN (FK_TABLE_NAME, REFERENCED_TABLE_NAME) 





SELECT * FROM T_CL_ZO_Table 

