
"use strict";

export function supportedMonthnames()
{ }


let monthNames: IT_SYS_Language_MonthNames[] = [
    {
        "SYSMONTHS_SYSLANG_LCID": 1033,
        "SYSMONTHS_MonthIndexBaseZero": 0,
        "SYSMONTHS_MonthIndexBaseOne": 1,
        "SYSMONTHS_SYSLANG_IetfLanguageTag": "en-US",
        "SYSMONTHS_Name": "January",
        "SYSMONTHS_LowerCaseName": "january",
        "SYSMONTHS_UpperCaseName": "JANUARY",
        "SYSMONTHS_TitleCaseName": "January",
        "SYSMONTHS_GenitiveName": "January",
        "SYSMONTHS_LowerCaseGenitiveName": "january",
        "SYSMONTHS_UpperCaseGenitiveName": "JANUARY",
        "SYSMONTHS_TitleCaseGenitiveName": "January",
        "SYSMONTHS_AbbreviatedName": "Jan",
        "SYSMONTHS_LowerCaseAbbreviatedName": "jan",
        "SYSMONTHS_UpperCaseAbbreviatedName": "JAN",
        "SYSMONTHS_TitleCaseAbbreviatedName": "Jan",
        "SYSMONTHS_AbbreviatedGenitiveName": "Jan",
        "SYSMONTHS_LowerCaseAbbreviatedGenitiveName": "jan",
        "SYSMONTHS_UpperCaseAbbreviatedGenitiveName": "JAN",
        "SYSMONTHS_TitleCaseAbbreviatedGenitiveName": "Jan"
    },
    {
        "SYSMONTHS_SYSLANG_LCID": 1033,
        "SYSMONTHS_MonthIndexBaseZero": 1,
        "SYSMONTHS_MonthIndexBaseOne": 2,
        "SYSMONTHS_SYSLANG_IetfLanguageTag": "en-US",
        "SYSMONTHS_Name": "February",
        "SYSMONTHS_LowerCaseName": "february",
        "SYSMONTHS_UpperCaseName": "FEBRUARY",
        "SYSMONTHS_TitleCaseName": "February",
        "SYSMONTHS_GenitiveName": "February",
        "SYSMONTHS_LowerCaseGenitiveName": "february",
        "SYSMONTHS_UpperCaseGenitiveName": "FEBRUARY",
        "SYSMONTHS_TitleCaseGenitiveName": "February",
        "SYSMONTHS_AbbreviatedName": "Feb",
        "SYSMONTHS_LowerCaseAbbreviatedName": "feb",
        "SYSMONTHS_UpperCaseAbbreviatedName": "FEB",
        "SYSMONTHS_TitleCaseAbbreviatedName": "Feb",
        "SYSMONTHS_AbbreviatedGenitiveName": "Feb",
        "SYSMONTHS_LowerCaseAbbreviatedGenitiveName": "feb",
        "SYSMONTHS_UpperCaseAbbreviatedGenitiveName": "FEB",
        "SYSMONTHS_TitleCaseAbbreviatedGenitiveName": "Feb"
    },
    {
        "SYSMONTHS_SYSLANG_LCID": 1033,
        "SYSMONTHS_MonthIndexBaseZero": 2,
        "SYSMONTHS_MonthIndexBaseOne": 3,
        "SYSMONTHS_SYSLANG_IetfLanguageTag": "en-US",
        "SYSMONTHS_Name": "March",
        "SYSMONTHS_LowerCaseName": "march",
        "SYSMONTHS_UpperCaseName": "MARCH",
        "SYSMONTHS_TitleCaseName": "March",
        "SYSMONTHS_GenitiveName": "March",
        "SYSMONTHS_LowerCaseGenitiveName": "march",
        "SYSMONTHS_UpperCaseGenitiveName": "MARCH",
        "SYSMONTHS_TitleCaseGenitiveName": "March",
        "SYSMONTHS_AbbreviatedName": "Mar",
        "SYSMONTHS_LowerCaseAbbreviatedName": "mar",
        "SYSMONTHS_UpperCaseAbbreviatedName": "MAR",
        "SYSMONTHS_TitleCaseAbbreviatedName": "Mar",
        "SYSMONTHS_AbbreviatedGenitiveName": "Mar",
        "SYSMONTHS_LowerCaseAbbreviatedGenitiveName": "mar",
        "SYSMONTHS_UpperCaseAbbreviatedGenitiveName": "MAR",
        "SYSMONTHS_TitleCaseAbbreviatedGenitiveName": "Mar"
    },
    {
        "SYSMONTHS_SYSLANG_LCID": 1033,
        "SYSMONTHS_MonthIndexBaseZero": 3,
        "SYSMONTHS_MonthIndexBaseOne": 4,
        "SYSMONTHS_SYSLANG_IetfLanguageTag": "en-US",
        "SYSMONTHS_Name": "April",
        "SYSMONTHS_LowerCaseName": "april",
        "SYSMONTHS_UpperCaseName": "APRIL",
        "SYSMONTHS_TitleCaseName": "April",
        "SYSMONTHS_GenitiveName": "April",
        "SYSMONTHS_LowerCaseGenitiveName": "april",
        "SYSMONTHS_UpperCaseGenitiveName": "APRIL",
        "SYSMONTHS_TitleCaseGenitiveName": "April",
        "SYSMONTHS_AbbreviatedName": "Apr",
        "SYSMONTHS_LowerCaseAbbreviatedName": "apr",
        "SYSMONTHS_UpperCaseAbbreviatedName": "APR",
        "SYSMONTHS_TitleCaseAbbreviatedName": "Apr",
        "SYSMONTHS_AbbreviatedGenitiveName": "Apr",
        "SYSMONTHS_LowerCaseAbbreviatedGenitiveName": "apr",
        "SYSMONTHS_UpperCaseAbbreviatedGenitiveName": "APR",
        "SYSMONTHS_TitleCaseAbbreviatedGenitiveName": "Apr"
    },
    {
        "SYSMONTHS_SYSLANG_LCID": 1033,
        "SYSMONTHS_MonthIndexBaseZero": 4,
        "SYSMONTHS_MonthIndexBaseOne": 5,
        "SYSMONTHS_SYSLANG_IetfLanguageTag": "en-US",
        "SYSMONTHS_Name": "May",
        "SYSMONTHS_LowerCaseName": "may",
        "SYSMONTHS_UpperCaseName": "MAY",
        "SYSMONTHS_TitleCaseName": "May",
        "SYSMONTHS_GenitiveName": "May",
        "SYSMONTHS_LowerCaseGenitiveName": "may",
        "SYSMONTHS_UpperCaseGenitiveName": "MAY",
        "SYSMONTHS_TitleCaseGenitiveName": "May",
        "SYSMONTHS_AbbreviatedName": "May",
        "SYSMONTHS_LowerCaseAbbreviatedName": "may",
        "SYSMONTHS_UpperCaseAbbreviatedName": "MAY",
        "SYSMONTHS_TitleCaseAbbreviatedName": "May",
        "SYSMONTHS_AbbreviatedGenitiveName": "May",
        "SYSMONTHS_LowerCaseAbbreviatedGenitiveName": "may",
        "SYSMONTHS_UpperCaseAbbreviatedGenitiveName": "MAY",
        "SYSMONTHS_TitleCaseAbbreviatedGenitiveName": "May"
    },
    {
        "SYSMONTHS_SYSLANG_LCID": 1033,
        "SYSMONTHS_MonthIndexBaseZero": 5,
        "SYSMONTHS_MonthIndexBaseOne": 6,
        "SYSMONTHS_SYSLANG_IetfLanguageTag": "en-US",
        "SYSMONTHS_Name": "June",
        "SYSMONTHS_LowerCaseName": "june",
        "SYSMONTHS_UpperCaseName": "JUNE",
        "SYSMONTHS_TitleCaseName": "June",
        "SYSMONTHS_GenitiveName": "June",
        "SYSMONTHS_LowerCaseGenitiveName": "june",
        "SYSMONTHS_UpperCaseGenitiveName": "JUNE",
        "SYSMONTHS_TitleCaseGenitiveName": "June",
        "SYSMONTHS_AbbreviatedName": "Jun",
        "SYSMONTHS_LowerCaseAbbreviatedName": "jun",
        "SYSMONTHS_UpperCaseAbbreviatedName": "JUN",
        "SYSMONTHS_TitleCaseAbbreviatedName": "Jun",
        "SYSMONTHS_AbbreviatedGenitiveName": "Jun",
        "SYSMONTHS_LowerCaseAbbreviatedGenitiveName": "jun",
        "SYSMONTHS_UpperCaseAbbreviatedGenitiveName": "JUN",
        "SYSMONTHS_TitleCaseAbbreviatedGenitiveName": "Jun"
    },
    {
        "SYSMONTHS_SYSLANG_LCID": 1033,
        "SYSMONTHS_MonthIndexBaseZero": 6,
        "SYSMONTHS_MonthIndexBaseOne": 7,
        "SYSMONTHS_SYSLANG_IetfLanguageTag": "en-US",
        "SYSMONTHS_Name": "July",
        "SYSMONTHS_LowerCaseName": "july",
        "SYSMONTHS_UpperCaseName": "JULY",
        "SYSMONTHS_TitleCaseName": "July",
        "SYSMONTHS_GenitiveName": "July",
        "SYSMONTHS_LowerCaseGenitiveName": "july",
        "SYSMONTHS_UpperCaseGenitiveName": "JULY",
        "SYSMONTHS_TitleCaseGenitiveName": "July",
        "SYSMONTHS_AbbreviatedName": "Jul",
        "SYSMONTHS_LowerCaseAbbreviatedName": "jul",
        "SYSMONTHS_UpperCaseAbbreviatedName": "JUL",
        "SYSMONTHS_TitleCaseAbbreviatedName": "Jul",
        "SYSMONTHS_AbbreviatedGenitiveName": "Jul",
        "SYSMONTHS_LowerCaseAbbreviatedGenitiveName": "jul",
        "SYSMONTHS_UpperCaseAbbreviatedGenitiveName": "JUL",
        "SYSMONTHS_TitleCaseAbbreviatedGenitiveName": "Jul"
    },
    {
        "SYSMONTHS_SYSLANG_LCID": 1033,
        "SYSMONTHS_MonthIndexBaseZero": 7,
        "SYSMONTHS_MonthIndexBaseOne": 8,
        "SYSMONTHS_SYSLANG_IetfLanguageTag": "en-US",
        "SYSMONTHS_Name": "August",
        "SYSMONTHS_LowerCaseName": "august",
        "SYSMONTHS_UpperCaseName": "AUGUST",
        "SYSMONTHS_TitleCaseName": "August",
        "SYSMONTHS_GenitiveName": "August",
        "SYSMONTHS_LowerCaseGenitiveName": "august",
        "SYSMONTHS_UpperCaseGenitiveName": "AUGUST",
        "SYSMONTHS_TitleCaseGenitiveName": "August",
        "SYSMONTHS_AbbreviatedName": "Aug",
        "SYSMONTHS_LowerCaseAbbreviatedName": "aug",
        "SYSMONTHS_UpperCaseAbbreviatedName": "AUG",
        "SYSMONTHS_TitleCaseAbbreviatedName": "Aug",
        "SYSMONTHS_AbbreviatedGenitiveName": "Aug",
        "SYSMONTHS_LowerCaseAbbreviatedGenitiveName": "aug",
        "SYSMONTHS_UpperCaseAbbreviatedGenitiveName": "AUG",
        "SYSMONTHS_TitleCaseAbbreviatedGenitiveName": "Aug"
    },
    {
        "SYSMONTHS_SYSLANG_LCID": 1033,
        "SYSMONTHS_MonthIndexBaseZero": 8,
        "SYSMONTHS_MonthIndexBaseOne": 9,
        "SYSMONTHS_SYSLANG_IetfLanguageTag": "en-US",
        "SYSMONTHS_Name": "September",
        "SYSMONTHS_LowerCaseName": "september",
        "SYSMONTHS_UpperCaseName": "SEPTEMBER",
        "SYSMONTHS_TitleCaseName": "September",
        "SYSMONTHS_GenitiveName": "September",
        "SYSMONTHS_LowerCaseGenitiveName": "september",
        "SYSMONTHS_UpperCaseGenitiveName": "SEPTEMBER",
        "SYSMONTHS_TitleCaseGenitiveName": "September",
        "SYSMONTHS_AbbreviatedName": "Sep",
        "SYSMONTHS_LowerCaseAbbreviatedName": "sep",
        "SYSMONTHS_UpperCaseAbbreviatedName": "SEP",
        "SYSMONTHS_TitleCaseAbbreviatedName": "Sep",
        "SYSMONTHS_AbbreviatedGenitiveName": "Sep",
        "SYSMONTHS_LowerCaseAbbreviatedGenitiveName": "sep",
        "SYSMONTHS_UpperCaseAbbreviatedGenitiveName": "SEP",
        "SYSMONTHS_TitleCaseAbbreviatedGenitiveName": "Sep"
    },
    {
        "SYSMONTHS_SYSLANG_LCID": 1033,
        "SYSMONTHS_MonthIndexBaseZero": 9,
        "SYSMONTHS_MonthIndexBaseOne": 10,
        "SYSMONTHS_SYSLANG_IetfLanguageTag": "en-US",
        "SYSMONTHS_Name": "October",
        "SYSMONTHS_LowerCaseName": "october",
        "SYSMONTHS_UpperCaseName": "OCTOBER",
        "SYSMONTHS_TitleCaseName": "October",
        "SYSMONTHS_GenitiveName": "October",
        "SYSMONTHS_LowerCaseGenitiveName": "october",
        "SYSMONTHS_UpperCaseGenitiveName": "OCTOBER",
        "SYSMONTHS_TitleCaseGenitiveName": "October",
        "SYSMONTHS_AbbreviatedName": "Oct",
        "SYSMONTHS_LowerCaseAbbreviatedName": "oct",
        "SYSMONTHS_UpperCaseAbbreviatedName": "OCT",
        "SYSMONTHS_TitleCaseAbbreviatedName": "Oct",
        "SYSMONTHS_AbbreviatedGenitiveName": "Oct",
        "SYSMONTHS_LowerCaseAbbreviatedGenitiveName": "oct",
        "SYSMONTHS_UpperCaseAbbreviatedGenitiveName": "OCT",
        "SYSMONTHS_TitleCaseAbbreviatedGenitiveName": "Oct"
    },
    {
        "SYSMONTHS_SYSLANG_LCID": 1033,
        "SYSMONTHS_MonthIndexBaseZero": 10,
        "SYSMONTHS_MonthIndexBaseOne": 11,
        "SYSMONTHS_SYSLANG_IetfLanguageTag": "en-US",
        "SYSMONTHS_Name": "November",
        "SYSMONTHS_LowerCaseName": "november",
        "SYSMONTHS_UpperCaseName": "NOVEMBER",
        "SYSMONTHS_TitleCaseName": "November",
        "SYSMONTHS_GenitiveName": "November",
        "SYSMONTHS_LowerCaseGenitiveName": "november",
        "SYSMONTHS_UpperCaseGenitiveName": "NOVEMBER",
        "SYSMONTHS_TitleCaseGenitiveName": "November",
        "SYSMONTHS_AbbreviatedName": "Nov",
        "SYSMONTHS_LowerCaseAbbreviatedName": "nov",
        "SYSMONTHS_UpperCaseAbbreviatedName": "NOV",
        "SYSMONTHS_TitleCaseAbbreviatedName": "Nov",
        "SYSMONTHS_AbbreviatedGenitiveName": "Nov",
        "SYSMONTHS_LowerCaseAbbreviatedGenitiveName": "nov",
        "SYSMONTHS_UpperCaseAbbreviatedGenitiveName": "NOV",
        "SYSMONTHS_TitleCaseAbbreviatedGenitiveName": "Nov"
    },
    {
        "SYSMONTHS_SYSLANG_LCID": 1033,
        "SYSMONTHS_MonthIndexBaseZero": 11,
        "SYSMONTHS_MonthIndexBaseOne": 12,
        "SYSMONTHS_SYSLANG_IetfLanguageTag": "en-US",
        "SYSMONTHS_Name": "December",
        "SYSMONTHS_LowerCaseName": "december",
        "SYSMONTHS_UpperCaseName": "DECEMBER",
        "SYSMONTHS_TitleCaseName": "December",
        "SYSMONTHS_GenitiveName": "December",
        "SYSMONTHS_LowerCaseGenitiveName": "december",
        "SYSMONTHS_UpperCaseGenitiveName": "DECEMBER",
        "SYSMONTHS_TitleCaseGenitiveName": "December",
        "SYSMONTHS_AbbreviatedName": "Dec",
        "SYSMONTHS_LowerCaseAbbreviatedName": "dec",
        "SYSMONTHS_UpperCaseAbbreviatedName": "DEC",
        "SYSMONTHS_TitleCaseAbbreviatedName": "Dec",
        "SYSMONTHS_AbbreviatedGenitiveName": "Dec",
        "SYSMONTHS_LowerCaseAbbreviatedGenitiveName": "dec",
        "SYSMONTHS_UpperCaseAbbreviatedGenitiveName": "DEC",
        "SYSMONTHS_TitleCaseAbbreviatedGenitiveName": "Dec"
    },
    {
        "SYSMONTHS_SYSLANG_LCID": 1047,
        "SYSMONTHS_MonthIndexBaseZero": 0,
        "SYSMONTHS_MonthIndexBaseOne": 1,
        "SYSMONTHS_SYSLANG_IetfLanguageTag": "rm-CH",
        "SYSMONTHS_Name": "schaner",
        "SYSMONTHS_LowerCaseName": "schaner",
        "SYSMONTHS_UpperCaseName": "SCHANER",
        "SYSMONTHS_TitleCaseName": "Schaner",
        "SYSMONTHS_GenitiveName": "da schaner",
        "SYSMONTHS_LowerCaseGenitiveName": "da schaner",
        "SYSMONTHS_UpperCaseGenitiveName": "DA SCHANER",
        "SYSMONTHS_TitleCaseGenitiveName": "Da Schaner",
        "SYSMONTHS_AbbreviatedName": "schan.",
        "SYSMONTHS_LowerCaseAbbreviatedName": "schan.",
        "SYSMONTHS_UpperCaseAbbreviatedName": "SCHAN.",
        "SYSMONTHS_TitleCaseAbbreviatedName": "Schan.",
        "SYSMONTHS_AbbreviatedGenitiveName": "da schan.",
        "SYSMONTHS_LowerCaseAbbreviatedGenitiveName": "da schan.",
        "SYSMONTHS_UpperCaseAbbreviatedGenitiveName": "DA SCHAN.",
        "SYSMONTHS_TitleCaseAbbreviatedGenitiveName": "Da Schan."
    },
    {
        "SYSMONTHS_SYSLANG_LCID": 1047,
        "SYSMONTHS_MonthIndexBaseZero": 1,
        "SYSMONTHS_MonthIndexBaseOne": 2,
        "SYSMONTHS_SYSLANG_IetfLanguageTag": "rm-CH",
        "SYSMONTHS_Name": "favrer",
        "SYSMONTHS_LowerCaseName": "favrer",
        "SYSMONTHS_UpperCaseName": "FAVRER",
        "SYSMONTHS_TitleCaseName": "Favrer",
        "SYSMONTHS_GenitiveName": "da favrer",
        "SYSMONTHS_LowerCaseGenitiveName": "da favrer",
        "SYSMONTHS_UpperCaseGenitiveName": "DA FAVRER",
        "SYSMONTHS_TitleCaseGenitiveName": "Da Favrer",
        "SYSMONTHS_AbbreviatedName": "favr.",
        "SYSMONTHS_LowerCaseAbbreviatedName": "favr.",
        "SYSMONTHS_UpperCaseAbbreviatedName": "FAVR.",
        "SYSMONTHS_TitleCaseAbbreviatedName": "Favr.",
        "SYSMONTHS_AbbreviatedGenitiveName": "da favr.",
        "SYSMONTHS_LowerCaseAbbreviatedGenitiveName": "da favr.",
        "SYSMONTHS_UpperCaseAbbreviatedGenitiveName": "DA FAVR.",
        "SYSMONTHS_TitleCaseAbbreviatedGenitiveName": "Da Favr."
    },
    {
        "SYSMONTHS_SYSLANG_LCID": 1047,
        "SYSMONTHS_MonthIndexBaseZero": 2,
        "SYSMONTHS_MonthIndexBaseOne": 3,
        "SYSMONTHS_SYSLANG_IetfLanguageTag": "rm-CH",
        "SYSMONTHS_Name": "mars",
        "SYSMONTHS_LowerCaseName": "mars",
        "SYSMONTHS_UpperCaseName": "MARS",
        "SYSMONTHS_TitleCaseName": "Mars",
        "SYSMONTHS_GenitiveName": "da mars",
        "SYSMONTHS_LowerCaseGenitiveName": "da mars",
        "SYSMONTHS_UpperCaseGenitiveName": "DA MARS",
        "SYSMONTHS_TitleCaseGenitiveName": "Da Mars",
        "SYSMONTHS_AbbreviatedName": "mars",
        "SYSMONTHS_LowerCaseAbbreviatedName": "mars",
        "SYSMONTHS_UpperCaseAbbreviatedName": "MARS",
        "SYSMONTHS_TitleCaseAbbreviatedName": "Mars",
        "SYSMONTHS_AbbreviatedGenitiveName": "da mars",
        "SYSMONTHS_LowerCaseAbbreviatedGenitiveName": "da mars",
        "SYSMONTHS_UpperCaseAbbreviatedGenitiveName": "DA MARS",
        "SYSMONTHS_TitleCaseAbbreviatedGenitiveName": "Da Mars"
    },
    {
        "SYSMONTHS_SYSLANG_LCID": 1047,
        "SYSMONTHS_MonthIndexBaseZero": 3,
        "SYSMONTHS_MonthIndexBaseOne": 4,
        "SYSMONTHS_SYSLANG_IetfLanguageTag": "rm-CH",
        "SYSMONTHS_Name": "avrigl",
        "SYSMONTHS_LowerCaseName": "avrigl",
        "SYSMONTHS_UpperCaseName": "AVRIGL",
        "SYSMONTHS_TitleCaseName": "Avrigl",
        "SYSMONTHS_GenitiveName": "d'avrigl",
        "SYSMONTHS_LowerCaseGenitiveName": "d'avrigl",
        "SYSMONTHS_UpperCaseGenitiveName": "D'AVRIGL",
        "SYSMONTHS_TitleCaseGenitiveName": "D'avrigl",
        "SYSMONTHS_AbbreviatedName": "avr.",
        "SYSMONTHS_LowerCaseAbbreviatedName": "avr.",
        "SYSMONTHS_UpperCaseAbbreviatedName": "AVR.",
        "SYSMONTHS_TitleCaseAbbreviatedName": "Avr.",
        "SYSMONTHS_AbbreviatedGenitiveName": "d'avr.",
        "SYSMONTHS_LowerCaseAbbreviatedGenitiveName": "d'avr.",
        "SYSMONTHS_UpperCaseAbbreviatedGenitiveName": "D'AVR.",
        "SYSMONTHS_TitleCaseAbbreviatedGenitiveName": "D'avr."
    },
    {
        "SYSMONTHS_SYSLANG_LCID": 1047,
        "SYSMONTHS_MonthIndexBaseZero": 4,
        "SYSMONTHS_MonthIndexBaseOne": 5,
        "SYSMONTHS_SYSLANG_IetfLanguageTag": "rm-CH",
        "SYSMONTHS_Name": "matg",
        "SYSMONTHS_LowerCaseName": "matg",
        "SYSMONTHS_UpperCaseName": "MATG",
        "SYSMONTHS_TitleCaseName": "Matg",
        "SYSMONTHS_GenitiveName": "da matg",
        "SYSMONTHS_LowerCaseGenitiveName": "da matg",
        "SYSMONTHS_UpperCaseGenitiveName": "DA MATG",
        "SYSMONTHS_TitleCaseGenitiveName": "Da Matg",
        "SYSMONTHS_AbbreviatedName": "matg",
        "SYSMONTHS_LowerCaseAbbreviatedName": "matg",
        "SYSMONTHS_UpperCaseAbbreviatedName": "MATG",
        "SYSMONTHS_TitleCaseAbbreviatedName": "Matg",
        "SYSMONTHS_AbbreviatedGenitiveName": "da matg",
        "SYSMONTHS_LowerCaseAbbreviatedGenitiveName": "da matg",
        "SYSMONTHS_UpperCaseAbbreviatedGenitiveName": "DA MATG",
        "SYSMONTHS_TitleCaseAbbreviatedGenitiveName": "Da Matg"
    },
    {
        "SYSMONTHS_SYSLANG_LCID": 1047,
        "SYSMONTHS_MonthIndexBaseZero": 5,
        "SYSMONTHS_MonthIndexBaseOne": 6,
        "SYSMONTHS_SYSLANG_IetfLanguageTag": "rm-CH",
        "SYSMONTHS_Name": "zercladur",
        "SYSMONTHS_LowerCaseName": "zercladur",
        "SYSMONTHS_UpperCaseName": "ZERCLADUR",
        "SYSMONTHS_TitleCaseName": "Zercladur",
        "SYSMONTHS_GenitiveName": "da zercladur",
        "SYSMONTHS_LowerCaseGenitiveName": "da zercladur",
        "SYSMONTHS_UpperCaseGenitiveName": "DA ZERCLADUR",
        "SYSMONTHS_TitleCaseGenitiveName": "Da Zercladur",
        "SYSMONTHS_AbbreviatedName": "zercl.",
        "SYSMONTHS_LowerCaseAbbreviatedName": "zercl.",
        "SYSMONTHS_UpperCaseAbbreviatedName": "ZERCL.",
        "SYSMONTHS_TitleCaseAbbreviatedName": "Zercl.",
        "SYSMONTHS_AbbreviatedGenitiveName": "da zercl.",
        "SYSMONTHS_LowerCaseAbbreviatedGenitiveName": "da zercl.",
        "SYSMONTHS_UpperCaseAbbreviatedGenitiveName": "DA ZERCL.",
        "SYSMONTHS_TitleCaseAbbreviatedGenitiveName": "Da Zercl."
    },
    {
        "SYSMONTHS_SYSLANG_LCID": 1047,
        "SYSMONTHS_MonthIndexBaseZero": 6,
        "SYSMONTHS_MonthIndexBaseOne": 7,
        "SYSMONTHS_SYSLANG_IetfLanguageTag": "rm-CH",
        "SYSMONTHS_Name": "fanadur",
        "SYSMONTHS_LowerCaseName": "fanadur",
        "SYSMONTHS_UpperCaseName": "FANADUR",
        "SYSMONTHS_TitleCaseName": "Fanadur",
        "SYSMONTHS_GenitiveName": "da fanadur",
        "SYSMONTHS_LowerCaseGenitiveName": "da fanadur",
        "SYSMONTHS_UpperCaseGenitiveName": "DA FANADUR",
        "SYSMONTHS_TitleCaseGenitiveName": "Da Fanadur",
        "SYSMONTHS_AbbreviatedName": "fan.",
        "SYSMONTHS_LowerCaseAbbreviatedName": "fan.",
        "SYSMONTHS_UpperCaseAbbreviatedName": "FAN.",
        "SYSMONTHS_TitleCaseAbbreviatedName": "Fan.",
        "SYSMONTHS_AbbreviatedGenitiveName": "da fan.",
        "SYSMONTHS_LowerCaseAbbreviatedGenitiveName": "da fan.",
        "SYSMONTHS_UpperCaseAbbreviatedGenitiveName": "DA FAN.",
        "SYSMONTHS_TitleCaseAbbreviatedGenitiveName": "Da Fan."
    },
    {
        "SYSMONTHS_SYSLANG_LCID": 1047,
        "SYSMONTHS_MonthIndexBaseZero": 7,
        "SYSMONTHS_MonthIndexBaseOne": 8,
        "SYSMONTHS_SYSLANG_IetfLanguageTag": "rm-CH",
        "SYSMONTHS_Name": "avust",
        "SYSMONTHS_LowerCaseName": "avust",
        "SYSMONTHS_UpperCaseName": "AVUST",
        "SYSMONTHS_TitleCaseName": "Avust",
        "SYSMONTHS_GenitiveName": "d'avust",
        "SYSMONTHS_LowerCaseGenitiveName": "d'avust",
        "SYSMONTHS_UpperCaseGenitiveName": "D'AVUST",
        "SYSMONTHS_TitleCaseGenitiveName": "D'avust",
        "SYSMONTHS_AbbreviatedName": "avust",
        "SYSMONTHS_LowerCaseAbbreviatedName": "avust",
        "SYSMONTHS_UpperCaseAbbreviatedName": "AVUST",
        "SYSMONTHS_TitleCaseAbbreviatedName": "Avust",
        "SYSMONTHS_AbbreviatedGenitiveName": "d'avust",
        "SYSMONTHS_LowerCaseAbbreviatedGenitiveName": "d'avust",
        "SYSMONTHS_UpperCaseAbbreviatedGenitiveName": "D'AVUST",
        "SYSMONTHS_TitleCaseAbbreviatedGenitiveName": "D'avust"
    },
    {
        "SYSMONTHS_SYSLANG_LCID": 1047,
        "SYSMONTHS_MonthIndexBaseZero": 8,
        "SYSMONTHS_MonthIndexBaseOne": 9,
        "SYSMONTHS_SYSLANG_IetfLanguageTag": "rm-CH",
        "SYSMONTHS_Name": "settember",
        "SYSMONTHS_LowerCaseName": "settember",
        "SYSMONTHS_UpperCaseName": "SETTEMBER",
        "SYSMONTHS_TitleCaseName": "Settember",
        "SYSMONTHS_GenitiveName": "da settember",
        "SYSMONTHS_LowerCaseGenitiveName": "da settember",
        "SYSMONTHS_UpperCaseGenitiveName": "DA SETTEMBER",
        "SYSMONTHS_TitleCaseGenitiveName": "Da Settember",
        "SYSMONTHS_AbbreviatedName": "sett.",
        "SYSMONTHS_LowerCaseAbbreviatedName": "sett.",
        "SYSMONTHS_UpperCaseAbbreviatedName": "SETT.",
        "SYSMONTHS_TitleCaseAbbreviatedName": "Sett.",
        "SYSMONTHS_AbbreviatedGenitiveName": "da sett.",
        "SYSMONTHS_LowerCaseAbbreviatedGenitiveName": "da sett.",
        "SYSMONTHS_UpperCaseAbbreviatedGenitiveName": "DA SETT.",
        "SYSMONTHS_TitleCaseAbbreviatedGenitiveName": "Da Sett."
    },
    {
        "SYSMONTHS_SYSLANG_LCID": 1047,
        "SYSMONTHS_MonthIndexBaseZero": 9,
        "SYSMONTHS_MonthIndexBaseOne": 10,
        "SYSMONTHS_SYSLANG_IetfLanguageTag": "rm-CH",
        "SYSMONTHS_Name": "october",
        "SYSMONTHS_LowerCaseName": "october",
        "SYSMONTHS_UpperCaseName": "OCTOBER",
        "SYSMONTHS_TitleCaseName": "October",
        "SYSMONTHS_GenitiveName": "d'october",
        "SYSMONTHS_LowerCaseGenitiveName": "d'october",
        "SYSMONTHS_UpperCaseGenitiveName": "D'OCTOBER",
        "SYSMONTHS_TitleCaseGenitiveName": "D'october",
        "SYSMONTHS_AbbreviatedName": "oct.",
        "SYSMONTHS_LowerCaseAbbreviatedName": "oct.",
        "SYSMONTHS_UpperCaseAbbreviatedName": "OCT.",
        "SYSMONTHS_TitleCaseAbbreviatedName": "Oct.",
        "SYSMONTHS_AbbreviatedGenitiveName": "d'oct.",
        "SYSMONTHS_LowerCaseAbbreviatedGenitiveName": "d'oct.",
        "SYSMONTHS_UpperCaseAbbreviatedGenitiveName": "D'OCT.",
        "SYSMONTHS_TitleCaseAbbreviatedGenitiveName": "D'oct."
    },
    {
        "SYSMONTHS_SYSLANG_LCID": 1047,
        "SYSMONTHS_MonthIndexBaseZero": 10,
        "SYSMONTHS_MonthIndexBaseOne": 11,
        "SYSMONTHS_SYSLANG_IetfLanguageTag": "rm-CH",
        "SYSMONTHS_Name": "november",
        "SYSMONTHS_LowerCaseName": "november",
        "SYSMONTHS_UpperCaseName": "NOVEMBER",
        "SYSMONTHS_TitleCaseName": "November",
        "SYSMONTHS_GenitiveName": "da november",
        "SYSMONTHS_LowerCaseGenitiveName": "da november",
        "SYSMONTHS_UpperCaseGenitiveName": "DA NOVEMBER",
        "SYSMONTHS_TitleCaseGenitiveName": "Da November",
        "SYSMONTHS_AbbreviatedName": "nov.",
        "SYSMONTHS_LowerCaseAbbreviatedName": "nov.",
        "SYSMONTHS_UpperCaseAbbreviatedName": "NOV.",
        "SYSMONTHS_TitleCaseAbbreviatedName": "Nov.",
        "SYSMONTHS_AbbreviatedGenitiveName": "da nov.",
        "SYSMONTHS_LowerCaseAbbreviatedGenitiveName": "da nov.",
        "SYSMONTHS_UpperCaseAbbreviatedGenitiveName": "DA NOV.",
        "SYSMONTHS_TitleCaseAbbreviatedGenitiveName": "Da Nov."
    },
    {
        "SYSMONTHS_SYSLANG_LCID": 1047,
        "SYSMONTHS_MonthIndexBaseZero": 11,
        "SYSMONTHS_MonthIndexBaseOne": 12,
        "SYSMONTHS_SYSLANG_IetfLanguageTag": "rm-CH",
        "SYSMONTHS_Name": "december",
        "SYSMONTHS_LowerCaseName": "december",
        "SYSMONTHS_UpperCaseName": "DECEMBER",
        "SYSMONTHS_TitleCaseName": "December",
        "SYSMONTHS_GenitiveName": "da december",
        "SYSMONTHS_LowerCaseGenitiveName": "da december",
        "SYSMONTHS_UpperCaseGenitiveName": "DA DECEMBER",
        "SYSMONTHS_TitleCaseGenitiveName": "Da December",
        "SYSMONTHS_AbbreviatedName": "dec.",
        "SYSMONTHS_LowerCaseAbbreviatedName": "dec.",
        "SYSMONTHS_UpperCaseAbbreviatedName": "DEC.",
        "SYSMONTHS_TitleCaseAbbreviatedName": "Dec.",
        "SYSMONTHS_AbbreviatedGenitiveName": "da dec.",
        "SYSMONTHS_LowerCaseAbbreviatedGenitiveName": "da dec.",
        "SYSMONTHS_UpperCaseAbbreviatedGenitiveName": "DA DEC.",
        "SYSMONTHS_TitleCaseAbbreviatedGenitiveName": "Da Dec."
    },
    {
        "SYSMONTHS_SYSLANG_LCID": 2055,
        "SYSMONTHS_MonthIndexBaseZero": 0,
        "SYSMONTHS_MonthIndexBaseOne": 1,
        "SYSMONTHS_SYSLANG_IetfLanguageTag": "de-CH",
        "SYSMONTHS_Name": "Januar",
        "SYSMONTHS_LowerCaseName": "januar",
        "SYSMONTHS_UpperCaseName": "JANUAR",
        "SYSMONTHS_TitleCaseName": "Januar",
        "SYSMONTHS_GenitiveName": "Januar",
        "SYSMONTHS_LowerCaseGenitiveName": "januar",
        "SYSMONTHS_UpperCaseGenitiveName": "JANUAR",
        "SYSMONTHS_TitleCaseGenitiveName": "Januar",
        "SYSMONTHS_AbbreviatedName": "Jan",
        "SYSMONTHS_LowerCaseAbbreviatedName": "jan",
        "SYSMONTHS_UpperCaseAbbreviatedName": "JAN",
        "SYSMONTHS_TitleCaseAbbreviatedName": "Jan",
        "SYSMONTHS_AbbreviatedGenitiveName": "Jan",
        "SYSMONTHS_LowerCaseAbbreviatedGenitiveName": "jan",
        "SYSMONTHS_UpperCaseAbbreviatedGenitiveName": "JAN",
        "SYSMONTHS_TitleCaseAbbreviatedGenitiveName": "Jan"
    },
    {
        "SYSMONTHS_SYSLANG_LCID": 2055,
        "SYSMONTHS_MonthIndexBaseZero": 1,
        "SYSMONTHS_MonthIndexBaseOne": 2,
        "SYSMONTHS_SYSLANG_IetfLanguageTag": "de-CH",
        "SYSMONTHS_Name": "Februar",
        "SYSMONTHS_LowerCaseName": "februar",
        "SYSMONTHS_UpperCaseName": "FEBRUAR",
        "SYSMONTHS_TitleCaseName": "Februar",
        "SYSMONTHS_GenitiveName": "Februar",
        "SYSMONTHS_LowerCaseGenitiveName": "februar",
        "SYSMONTHS_UpperCaseGenitiveName": "FEBRUAR",
        "SYSMONTHS_TitleCaseGenitiveName": "Februar",
        "SYSMONTHS_AbbreviatedName": "Feb",
        "SYSMONTHS_LowerCaseAbbreviatedName": "feb",
        "SYSMONTHS_UpperCaseAbbreviatedName": "FEB",
        "SYSMONTHS_TitleCaseAbbreviatedName": "Feb",
        "SYSMONTHS_AbbreviatedGenitiveName": "Feb",
        "SYSMONTHS_LowerCaseAbbreviatedGenitiveName": "feb",
        "SYSMONTHS_UpperCaseAbbreviatedGenitiveName": "FEB",
        "SYSMONTHS_TitleCaseAbbreviatedGenitiveName": "Feb"
    },
    {
        "SYSMONTHS_SYSLANG_LCID": 2055,
        "SYSMONTHS_MonthIndexBaseZero": 2,
        "SYSMONTHS_MonthIndexBaseOne": 3,
        "SYSMONTHS_SYSLANG_IetfLanguageTag": "de-CH",
        "SYSMONTHS_Name": "März",
        "SYSMONTHS_LowerCaseName": "märz",
        "SYSMONTHS_UpperCaseName": "MÄRZ",
        "SYSMONTHS_TitleCaseName": "März",
        "SYSMONTHS_GenitiveName": "März",
        "SYSMONTHS_LowerCaseGenitiveName": "märz",
        "SYSMONTHS_UpperCaseGenitiveName": "MÄRZ",
        "SYSMONTHS_TitleCaseGenitiveName": "März",
        "SYSMONTHS_AbbreviatedName": "Mrz",
        "SYSMONTHS_LowerCaseAbbreviatedName": "mrz",
        "SYSMONTHS_UpperCaseAbbreviatedName": "MRZ",
        "SYSMONTHS_TitleCaseAbbreviatedName": "Mrz",
        "SYSMONTHS_AbbreviatedGenitiveName": "Mrz",
        "SYSMONTHS_LowerCaseAbbreviatedGenitiveName": "mrz",
        "SYSMONTHS_UpperCaseAbbreviatedGenitiveName": "MRZ",
        "SYSMONTHS_TitleCaseAbbreviatedGenitiveName": "Mrz"
    },
    {
        "SYSMONTHS_SYSLANG_LCID": 2055,
        "SYSMONTHS_MonthIndexBaseZero": 3,
        "SYSMONTHS_MonthIndexBaseOne": 4,
        "SYSMONTHS_SYSLANG_IetfLanguageTag": "de-CH",
        "SYSMONTHS_Name": "April",
        "SYSMONTHS_LowerCaseName": "april",
        "SYSMONTHS_UpperCaseName": "APRIL",
        "SYSMONTHS_TitleCaseName": "April",
        "SYSMONTHS_GenitiveName": "April",
        "SYSMONTHS_LowerCaseGenitiveName": "april",
        "SYSMONTHS_UpperCaseGenitiveName": "APRIL",
        "SYSMONTHS_TitleCaseGenitiveName": "April",
        "SYSMONTHS_AbbreviatedName": "Apr",
        "SYSMONTHS_LowerCaseAbbreviatedName": "apr",
        "SYSMONTHS_UpperCaseAbbreviatedName": "APR",
        "SYSMONTHS_TitleCaseAbbreviatedName": "Apr",
        "SYSMONTHS_AbbreviatedGenitiveName": "Apr",
        "SYSMONTHS_LowerCaseAbbreviatedGenitiveName": "apr",
        "SYSMONTHS_UpperCaseAbbreviatedGenitiveName": "APR",
        "SYSMONTHS_TitleCaseAbbreviatedGenitiveName": "Apr"
    },
    {
        "SYSMONTHS_SYSLANG_LCID": 2055,
        "SYSMONTHS_MonthIndexBaseZero": 4,
        "SYSMONTHS_MonthIndexBaseOne": 5,
        "SYSMONTHS_SYSLANG_IetfLanguageTag": "de-CH",
        "SYSMONTHS_Name": "Mai",
        "SYSMONTHS_LowerCaseName": "mai",
        "SYSMONTHS_UpperCaseName": "MAI",
        "SYSMONTHS_TitleCaseName": "Mai",
        "SYSMONTHS_GenitiveName": "Mai",
        "SYSMONTHS_LowerCaseGenitiveName": "mai",
        "SYSMONTHS_UpperCaseGenitiveName": "MAI",
        "SYSMONTHS_TitleCaseGenitiveName": "Mai",
        "SYSMONTHS_AbbreviatedName": "Mai",
        "SYSMONTHS_LowerCaseAbbreviatedName": "mai",
        "SYSMONTHS_UpperCaseAbbreviatedName": "MAI",
        "SYSMONTHS_TitleCaseAbbreviatedName": "Mai",
        "SYSMONTHS_AbbreviatedGenitiveName": "Mai",
        "SYSMONTHS_LowerCaseAbbreviatedGenitiveName": "mai",
        "SYSMONTHS_UpperCaseAbbreviatedGenitiveName": "MAI",
        "SYSMONTHS_TitleCaseAbbreviatedGenitiveName": "Mai"
    },
    {
        "SYSMONTHS_SYSLANG_LCID": 2055,
        "SYSMONTHS_MonthIndexBaseZero": 5,
        "SYSMONTHS_MonthIndexBaseOne": 6,
        "SYSMONTHS_SYSLANG_IetfLanguageTag": "de-CH",
        "SYSMONTHS_Name": "Juni",
        "SYSMONTHS_LowerCaseName": "juni",
        "SYSMONTHS_UpperCaseName": "JUNI",
        "SYSMONTHS_TitleCaseName": "Juni",
        "SYSMONTHS_GenitiveName": "Juni",
        "SYSMONTHS_LowerCaseGenitiveName": "juni",
        "SYSMONTHS_UpperCaseGenitiveName": "JUNI",
        "SYSMONTHS_TitleCaseGenitiveName": "Juni",
        "SYSMONTHS_AbbreviatedName": "Jun",
        "SYSMONTHS_LowerCaseAbbreviatedName": "jun",
        "SYSMONTHS_UpperCaseAbbreviatedName": "JUN",
        "SYSMONTHS_TitleCaseAbbreviatedName": "Jun",
        "SYSMONTHS_AbbreviatedGenitiveName": "Jun",
        "SYSMONTHS_LowerCaseAbbreviatedGenitiveName": "jun",
        "SYSMONTHS_UpperCaseAbbreviatedGenitiveName": "JUN",
        "SYSMONTHS_TitleCaseAbbreviatedGenitiveName": "Jun"
    },
    {
        "SYSMONTHS_SYSLANG_LCID": 2055,
        "SYSMONTHS_MonthIndexBaseZero": 6,
        "SYSMONTHS_MonthIndexBaseOne": 7,
        "SYSMONTHS_SYSLANG_IetfLanguageTag": "de-CH",
        "SYSMONTHS_Name": "Juli",
        "SYSMONTHS_LowerCaseName": "juli",
        "SYSMONTHS_UpperCaseName": "JULI",
        "SYSMONTHS_TitleCaseName": "Juli",
        "SYSMONTHS_GenitiveName": "Juli",
        "SYSMONTHS_LowerCaseGenitiveName": "juli",
        "SYSMONTHS_UpperCaseGenitiveName": "JULI",
        "SYSMONTHS_TitleCaseGenitiveName": "Juli",
        "SYSMONTHS_AbbreviatedName": "Jul",
        "SYSMONTHS_LowerCaseAbbreviatedName": "jul",
        "SYSMONTHS_UpperCaseAbbreviatedName": "JUL",
        "SYSMONTHS_TitleCaseAbbreviatedName": "Jul",
        "SYSMONTHS_AbbreviatedGenitiveName": "Jul",
        "SYSMONTHS_LowerCaseAbbreviatedGenitiveName": "jul",
        "SYSMONTHS_UpperCaseAbbreviatedGenitiveName": "JUL",
        "SYSMONTHS_TitleCaseAbbreviatedGenitiveName": "Jul"
    },
    {
        "SYSMONTHS_SYSLANG_LCID": 2055,
        "SYSMONTHS_MonthIndexBaseZero": 7,
        "SYSMONTHS_MonthIndexBaseOne": 8,
        "SYSMONTHS_SYSLANG_IetfLanguageTag": "de-CH",
        "SYSMONTHS_Name": "August",
        "SYSMONTHS_LowerCaseName": "august",
        "SYSMONTHS_UpperCaseName": "AUGUST",
        "SYSMONTHS_TitleCaseName": "August",
        "SYSMONTHS_GenitiveName": "August",
        "SYSMONTHS_LowerCaseGenitiveName": "august",
        "SYSMONTHS_UpperCaseGenitiveName": "AUGUST",
        "SYSMONTHS_TitleCaseGenitiveName": "August",
        "SYSMONTHS_AbbreviatedName": "Aug",
        "SYSMONTHS_LowerCaseAbbreviatedName": "aug",
        "SYSMONTHS_UpperCaseAbbreviatedName": "AUG",
        "SYSMONTHS_TitleCaseAbbreviatedName": "Aug",
        "SYSMONTHS_AbbreviatedGenitiveName": "Aug",
        "SYSMONTHS_LowerCaseAbbreviatedGenitiveName": "aug",
        "SYSMONTHS_UpperCaseAbbreviatedGenitiveName": "AUG",
        "SYSMONTHS_TitleCaseAbbreviatedGenitiveName": "Aug"
    },
    {
        "SYSMONTHS_SYSLANG_LCID": 2055,
        "SYSMONTHS_MonthIndexBaseZero": 8,
        "SYSMONTHS_MonthIndexBaseOne": 9,
        "SYSMONTHS_SYSLANG_IetfLanguageTag": "de-CH",
        "SYSMONTHS_Name": "September",
        "SYSMONTHS_LowerCaseName": "september",
        "SYSMONTHS_UpperCaseName": "SEPTEMBER",
        "SYSMONTHS_TitleCaseName": "September",
        "SYSMONTHS_GenitiveName": "September",
        "SYSMONTHS_LowerCaseGenitiveName": "september",
        "SYSMONTHS_UpperCaseGenitiveName": "SEPTEMBER",
        "SYSMONTHS_TitleCaseGenitiveName": "September",
        "SYSMONTHS_AbbreviatedName": "Sep",
        "SYSMONTHS_LowerCaseAbbreviatedName": "sep",
        "SYSMONTHS_UpperCaseAbbreviatedName": "SEP",
        "SYSMONTHS_TitleCaseAbbreviatedName": "Sep",
        "SYSMONTHS_AbbreviatedGenitiveName": "Sep",
        "SYSMONTHS_LowerCaseAbbreviatedGenitiveName": "sep",
        "SYSMONTHS_UpperCaseAbbreviatedGenitiveName": "SEP",
        "SYSMONTHS_TitleCaseAbbreviatedGenitiveName": "Sep"
    },
    {
        "SYSMONTHS_SYSLANG_LCID": 2055,
        "SYSMONTHS_MonthIndexBaseZero": 9,
        "SYSMONTHS_MonthIndexBaseOne": 10,
        "SYSMONTHS_SYSLANG_IetfLanguageTag": "de-CH",
        "SYSMONTHS_Name": "Oktober",
        "SYSMONTHS_LowerCaseName": "oktober",
        "SYSMONTHS_UpperCaseName": "OKTOBER",
        "SYSMONTHS_TitleCaseName": "Oktober",
        "SYSMONTHS_GenitiveName": "Oktober",
        "SYSMONTHS_LowerCaseGenitiveName": "oktober",
        "SYSMONTHS_UpperCaseGenitiveName": "OKTOBER",
        "SYSMONTHS_TitleCaseGenitiveName": "Oktober",
        "SYSMONTHS_AbbreviatedName": "Okt",
        "SYSMONTHS_LowerCaseAbbreviatedName": "okt",
        "SYSMONTHS_UpperCaseAbbreviatedName": "OKT",
        "SYSMONTHS_TitleCaseAbbreviatedName": "Okt",
        "SYSMONTHS_AbbreviatedGenitiveName": "Okt",
        "SYSMONTHS_LowerCaseAbbreviatedGenitiveName": "okt",
        "SYSMONTHS_UpperCaseAbbreviatedGenitiveName": "OKT",
        "SYSMONTHS_TitleCaseAbbreviatedGenitiveName": "Okt"
    },
    {
        "SYSMONTHS_SYSLANG_LCID": 2055,
        "SYSMONTHS_MonthIndexBaseZero": 10,
        "SYSMONTHS_MonthIndexBaseOne": 11,
        "SYSMONTHS_SYSLANG_IetfLanguageTag": "de-CH",
        "SYSMONTHS_Name": "November",
        "SYSMONTHS_LowerCaseName": "november",
        "SYSMONTHS_UpperCaseName": "NOVEMBER",
        "SYSMONTHS_TitleCaseName": "November",
        "SYSMONTHS_GenitiveName": "November",
        "SYSMONTHS_LowerCaseGenitiveName": "november",
        "SYSMONTHS_UpperCaseGenitiveName": "NOVEMBER",
        "SYSMONTHS_TitleCaseGenitiveName": "November",
        "SYSMONTHS_AbbreviatedName": "Nov",
        "SYSMONTHS_LowerCaseAbbreviatedName": "nov",
        "SYSMONTHS_UpperCaseAbbreviatedName": "NOV",
        "SYSMONTHS_TitleCaseAbbreviatedName": "Nov",
        "SYSMONTHS_AbbreviatedGenitiveName": "Nov",
        "SYSMONTHS_LowerCaseAbbreviatedGenitiveName": "nov",
        "SYSMONTHS_UpperCaseAbbreviatedGenitiveName": "NOV",
        "SYSMONTHS_TitleCaseAbbreviatedGenitiveName": "Nov"
    },
    {
        "SYSMONTHS_SYSLANG_LCID": 2055,
        "SYSMONTHS_MonthIndexBaseZero": 11,
        "SYSMONTHS_MonthIndexBaseOne": 12,
        "SYSMONTHS_SYSLANG_IetfLanguageTag": "de-CH",
        "SYSMONTHS_Name": "Dezember",
        "SYSMONTHS_LowerCaseName": "dezember",
        "SYSMONTHS_UpperCaseName": "DEZEMBER",
        "SYSMONTHS_TitleCaseName": "Dezember",
        "SYSMONTHS_GenitiveName": "Dezember",
        "SYSMONTHS_LowerCaseGenitiveName": "dezember",
        "SYSMONTHS_UpperCaseGenitiveName": "DEZEMBER",
        "SYSMONTHS_TitleCaseGenitiveName": "Dezember",
        "SYSMONTHS_AbbreviatedName": "Dez",
        "SYSMONTHS_LowerCaseAbbreviatedName": "dez",
        "SYSMONTHS_UpperCaseAbbreviatedName": "DEZ",
        "SYSMONTHS_TitleCaseAbbreviatedName": "Dez",
        "SYSMONTHS_AbbreviatedGenitiveName": "Dez",
        "SYSMONTHS_LowerCaseAbbreviatedGenitiveName": "dez",
        "SYSMONTHS_UpperCaseAbbreviatedGenitiveName": "DEZ",
        "SYSMONTHS_TitleCaseAbbreviatedGenitiveName": "Dez"
    },
    {
        "SYSMONTHS_SYSLANG_LCID": 2064,
        "SYSMONTHS_MonthIndexBaseZero": 0,
        "SYSMONTHS_MonthIndexBaseOne": 1,
        "SYSMONTHS_SYSLANG_IetfLanguageTag": "it-CH",
        "SYSMONTHS_Name": "gennaio",
        "SYSMONTHS_LowerCaseName": "gennaio",
        "SYSMONTHS_UpperCaseName": "GENNAIO",
        "SYSMONTHS_TitleCaseName": "Gennaio",
        "SYSMONTHS_GenitiveName": "gennaio",
        "SYSMONTHS_LowerCaseGenitiveName": "gennaio",
        "SYSMONTHS_UpperCaseGenitiveName": "GENNAIO",
        "SYSMONTHS_TitleCaseGenitiveName": "Gennaio",
        "SYSMONTHS_AbbreviatedName": "gen",
        "SYSMONTHS_LowerCaseAbbreviatedName": "gen",
        "SYSMONTHS_UpperCaseAbbreviatedName": "GEN",
        "SYSMONTHS_TitleCaseAbbreviatedName": "Gen",
        "SYSMONTHS_AbbreviatedGenitiveName": "gen",
        "SYSMONTHS_LowerCaseAbbreviatedGenitiveName": "gen",
        "SYSMONTHS_UpperCaseAbbreviatedGenitiveName": "GEN",
        "SYSMONTHS_TitleCaseAbbreviatedGenitiveName": "Gen"
    },
    {
        "SYSMONTHS_SYSLANG_LCID": 2064,
        "SYSMONTHS_MonthIndexBaseZero": 1,
        "SYSMONTHS_MonthIndexBaseOne": 2,
        "SYSMONTHS_SYSLANG_IetfLanguageTag": "it-CH",
        "SYSMONTHS_Name": "febbraio",
        "SYSMONTHS_LowerCaseName": "febbraio",
        "SYSMONTHS_UpperCaseName": "FEBBRAIO",
        "SYSMONTHS_TitleCaseName": "Febbraio",
        "SYSMONTHS_GenitiveName": "febbraio",
        "SYSMONTHS_LowerCaseGenitiveName": "febbraio",
        "SYSMONTHS_UpperCaseGenitiveName": "FEBBRAIO",
        "SYSMONTHS_TitleCaseGenitiveName": "Febbraio",
        "SYSMONTHS_AbbreviatedName": "feb",
        "SYSMONTHS_LowerCaseAbbreviatedName": "feb",
        "SYSMONTHS_UpperCaseAbbreviatedName": "FEB",
        "SYSMONTHS_TitleCaseAbbreviatedName": "Feb",
        "SYSMONTHS_AbbreviatedGenitiveName": "feb",
        "SYSMONTHS_LowerCaseAbbreviatedGenitiveName": "feb",
        "SYSMONTHS_UpperCaseAbbreviatedGenitiveName": "FEB",
        "SYSMONTHS_TitleCaseAbbreviatedGenitiveName": "Feb"
    },
    {
        "SYSMONTHS_SYSLANG_LCID": 2064,
        "SYSMONTHS_MonthIndexBaseZero": 2,
        "SYSMONTHS_MonthIndexBaseOne": 3,
        "SYSMONTHS_SYSLANG_IetfLanguageTag": "it-CH",
        "SYSMONTHS_Name": "marzo",
        "SYSMONTHS_LowerCaseName": "marzo",
        "SYSMONTHS_UpperCaseName": "MARZO",
        "SYSMONTHS_TitleCaseName": "Marzo",
        "SYSMONTHS_GenitiveName": "marzo",
        "SYSMONTHS_LowerCaseGenitiveName": "marzo",
        "SYSMONTHS_UpperCaseGenitiveName": "MARZO",
        "SYSMONTHS_TitleCaseGenitiveName": "Marzo",
        "SYSMONTHS_AbbreviatedName": "mar",
        "SYSMONTHS_LowerCaseAbbreviatedName": "mar",
        "SYSMONTHS_UpperCaseAbbreviatedName": "MAR",
        "SYSMONTHS_TitleCaseAbbreviatedName": "Mar",
        "SYSMONTHS_AbbreviatedGenitiveName": "mar",
        "SYSMONTHS_LowerCaseAbbreviatedGenitiveName": "mar",
        "SYSMONTHS_UpperCaseAbbreviatedGenitiveName": "MAR",
        "SYSMONTHS_TitleCaseAbbreviatedGenitiveName": "Mar"
    },
    {
        "SYSMONTHS_SYSLANG_LCID": 2064,
        "SYSMONTHS_MonthIndexBaseZero": 3,
        "SYSMONTHS_MonthIndexBaseOne": 4,
        "SYSMONTHS_SYSLANG_IetfLanguageTag": "it-CH",
        "SYSMONTHS_Name": "aprile",
        "SYSMONTHS_LowerCaseName": "aprile",
        "SYSMONTHS_UpperCaseName": "APRILE",
        "SYSMONTHS_TitleCaseName": "Aprile",
        "SYSMONTHS_GenitiveName": "aprile",
        "SYSMONTHS_LowerCaseGenitiveName": "aprile",
        "SYSMONTHS_UpperCaseGenitiveName": "APRILE",
        "SYSMONTHS_TitleCaseGenitiveName": "Aprile",
        "SYSMONTHS_AbbreviatedName": "apr",
        "SYSMONTHS_LowerCaseAbbreviatedName": "apr",
        "SYSMONTHS_UpperCaseAbbreviatedName": "APR",
        "SYSMONTHS_TitleCaseAbbreviatedName": "Apr",
        "SYSMONTHS_AbbreviatedGenitiveName": "apr",
        "SYSMONTHS_LowerCaseAbbreviatedGenitiveName": "apr",
        "SYSMONTHS_UpperCaseAbbreviatedGenitiveName": "APR",
        "SYSMONTHS_TitleCaseAbbreviatedGenitiveName": "Apr"
    },
    {
        "SYSMONTHS_SYSLANG_LCID": 2064,
        "SYSMONTHS_MonthIndexBaseZero": 4,
        "SYSMONTHS_MonthIndexBaseOne": 5,
        "SYSMONTHS_SYSLANG_IetfLanguageTag": "it-CH",
        "SYSMONTHS_Name": "maggio",
        "SYSMONTHS_LowerCaseName": "maggio",
        "SYSMONTHS_UpperCaseName": "MAGGIO",
        "SYSMONTHS_TitleCaseName": "Maggio",
        "SYSMONTHS_GenitiveName": "maggio",
        "SYSMONTHS_LowerCaseGenitiveName": "maggio",
        "SYSMONTHS_UpperCaseGenitiveName": "MAGGIO",
        "SYSMONTHS_TitleCaseGenitiveName": "Maggio",
        "SYSMONTHS_AbbreviatedName": "mag",
        "SYSMONTHS_LowerCaseAbbreviatedName": "mag",
        "SYSMONTHS_UpperCaseAbbreviatedName": "MAG",
        "SYSMONTHS_TitleCaseAbbreviatedName": "Mag",
        "SYSMONTHS_AbbreviatedGenitiveName": "mag",
        "SYSMONTHS_LowerCaseAbbreviatedGenitiveName": "mag",
        "SYSMONTHS_UpperCaseAbbreviatedGenitiveName": "MAG",
        "SYSMONTHS_TitleCaseAbbreviatedGenitiveName": "Mag"
    },
    {
        "SYSMONTHS_SYSLANG_LCID": 2064,
        "SYSMONTHS_MonthIndexBaseZero": 5,
        "SYSMONTHS_MonthIndexBaseOne": 6,
        "SYSMONTHS_SYSLANG_IetfLanguageTag": "it-CH",
        "SYSMONTHS_Name": "giugno",
        "SYSMONTHS_LowerCaseName": "giugno",
        "SYSMONTHS_UpperCaseName": "GIUGNO",
        "SYSMONTHS_TitleCaseName": "Giugno",
        "SYSMONTHS_GenitiveName": "giugno",
        "SYSMONTHS_LowerCaseGenitiveName": "giugno",
        "SYSMONTHS_UpperCaseGenitiveName": "GIUGNO",
        "SYSMONTHS_TitleCaseGenitiveName": "Giugno",
        "SYSMONTHS_AbbreviatedName": "gio",
        "SYSMONTHS_LowerCaseAbbreviatedName": "gio",
        "SYSMONTHS_UpperCaseAbbreviatedName": "GIO",
        "SYSMONTHS_TitleCaseAbbreviatedName": "Gio",
        "SYSMONTHS_AbbreviatedGenitiveName": "gio",
        "SYSMONTHS_LowerCaseAbbreviatedGenitiveName": "gio",
        "SYSMONTHS_UpperCaseAbbreviatedGenitiveName": "GIO",
        "SYSMONTHS_TitleCaseAbbreviatedGenitiveName": "Gio"
    },
    {
        "SYSMONTHS_SYSLANG_LCID": 2064,
        "SYSMONTHS_MonthIndexBaseZero": 6,
        "SYSMONTHS_MonthIndexBaseOne": 7,
        "SYSMONTHS_SYSLANG_IetfLanguageTag": "it-CH",
        "SYSMONTHS_Name": "luglio",
        "SYSMONTHS_LowerCaseName": "luglio",
        "SYSMONTHS_UpperCaseName": "LUGLIO",
        "SYSMONTHS_TitleCaseName": "Luglio",
        "SYSMONTHS_GenitiveName": "luglio",
        "SYSMONTHS_LowerCaseGenitiveName": "luglio",
        "SYSMONTHS_UpperCaseGenitiveName": "LUGLIO",
        "SYSMONTHS_TitleCaseGenitiveName": "Luglio",
        "SYSMONTHS_AbbreviatedName": "lug",
        "SYSMONTHS_LowerCaseAbbreviatedName": "lug",
        "SYSMONTHS_UpperCaseAbbreviatedName": "LUG",
        "SYSMONTHS_TitleCaseAbbreviatedName": "Lug",
        "SYSMONTHS_AbbreviatedGenitiveName": "lug",
        "SYSMONTHS_LowerCaseAbbreviatedGenitiveName": "lug",
        "SYSMONTHS_UpperCaseAbbreviatedGenitiveName": "LUG",
        "SYSMONTHS_TitleCaseAbbreviatedGenitiveName": "Lug"
    },
    {
        "SYSMONTHS_SYSLANG_LCID": 2064,
        "SYSMONTHS_MonthIndexBaseZero": 7,
        "SYSMONTHS_MonthIndexBaseOne": 8,
        "SYSMONTHS_SYSLANG_IetfLanguageTag": "it-CH",
        "SYSMONTHS_Name": "agosto",
        "SYSMONTHS_LowerCaseName": "agosto",
        "SYSMONTHS_UpperCaseName": "AGOSTO",
        "SYSMONTHS_TitleCaseName": "Agosto",
        "SYSMONTHS_GenitiveName": "agosto",
        "SYSMONTHS_LowerCaseGenitiveName": "agosto",
        "SYSMONTHS_UpperCaseGenitiveName": "AGOSTO",
        "SYSMONTHS_TitleCaseGenitiveName": "Agosto",
        "SYSMONTHS_AbbreviatedName": "ago",
        "SYSMONTHS_LowerCaseAbbreviatedName": "ago",
        "SYSMONTHS_UpperCaseAbbreviatedName": "AGO",
        "SYSMONTHS_TitleCaseAbbreviatedName": "Ago",
        "SYSMONTHS_AbbreviatedGenitiveName": "ago",
        "SYSMONTHS_LowerCaseAbbreviatedGenitiveName": "ago",
        "SYSMONTHS_UpperCaseAbbreviatedGenitiveName": "AGO",
        "SYSMONTHS_TitleCaseAbbreviatedGenitiveName": "Ago"
    },
    {
        "SYSMONTHS_SYSLANG_LCID": 2064,
        "SYSMONTHS_MonthIndexBaseZero": 8,
        "SYSMONTHS_MonthIndexBaseOne": 9,
        "SYSMONTHS_SYSLANG_IetfLanguageTag": "it-CH",
        "SYSMONTHS_Name": "settembre",
        "SYSMONTHS_LowerCaseName": "settembre",
        "SYSMONTHS_UpperCaseName": "SETTEMBRE",
        "SYSMONTHS_TitleCaseName": "Settembre",
        "SYSMONTHS_GenitiveName": "settembre",
        "SYSMONTHS_LowerCaseGenitiveName": "settembre",
        "SYSMONTHS_UpperCaseGenitiveName": "SETTEMBRE",
        "SYSMONTHS_TitleCaseGenitiveName": "Settembre",
        "SYSMONTHS_AbbreviatedName": "set",
        "SYSMONTHS_LowerCaseAbbreviatedName": "set",
        "SYSMONTHS_UpperCaseAbbreviatedName": "SET",
        "SYSMONTHS_TitleCaseAbbreviatedName": "Set",
        "SYSMONTHS_AbbreviatedGenitiveName": "set",
        "SYSMONTHS_LowerCaseAbbreviatedGenitiveName": "set",
        "SYSMONTHS_UpperCaseAbbreviatedGenitiveName": "SET",
        "SYSMONTHS_TitleCaseAbbreviatedGenitiveName": "Set"
    },
    {
        "SYSMONTHS_SYSLANG_LCID": 2064,
        "SYSMONTHS_MonthIndexBaseZero": 9,
        "SYSMONTHS_MonthIndexBaseOne": 10,
        "SYSMONTHS_SYSLANG_IetfLanguageTag": "it-CH",
        "SYSMONTHS_Name": "ottobre",
        "SYSMONTHS_LowerCaseName": "ottobre",
        "SYSMONTHS_UpperCaseName": "OTTOBRE",
        "SYSMONTHS_TitleCaseName": "Ottobre",
        "SYSMONTHS_GenitiveName": "ottobre",
        "SYSMONTHS_LowerCaseGenitiveName": "ottobre",
        "SYSMONTHS_UpperCaseGenitiveName": "OTTOBRE",
        "SYSMONTHS_TitleCaseGenitiveName": "Ottobre",
        "SYSMONTHS_AbbreviatedName": "ott",
        "SYSMONTHS_LowerCaseAbbreviatedName": "ott",
        "SYSMONTHS_UpperCaseAbbreviatedName": "OTT",
        "SYSMONTHS_TitleCaseAbbreviatedName": "Ott",
        "SYSMONTHS_AbbreviatedGenitiveName": "ott",
        "SYSMONTHS_LowerCaseAbbreviatedGenitiveName": "ott",
        "SYSMONTHS_UpperCaseAbbreviatedGenitiveName": "OTT",
        "SYSMONTHS_TitleCaseAbbreviatedGenitiveName": "Ott"
    },
    {
        "SYSMONTHS_SYSLANG_LCID": 2064,
        "SYSMONTHS_MonthIndexBaseZero": 10,
        "SYSMONTHS_MonthIndexBaseOne": 11,
        "SYSMONTHS_SYSLANG_IetfLanguageTag": "it-CH",
        "SYSMONTHS_Name": "novembre",
        "SYSMONTHS_LowerCaseName": "novembre",
        "SYSMONTHS_UpperCaseName": "NOVEMBRE",
        "SYSMONTHS_TitleCaseName": "Novembre",
        "SYSMONTHS_GenitiveName": "novembre",
        "SYSMONTHS_LowerCaseGenitiveName": "novembre",
        "SYSMONTHS_UpperCaseGenitiveName": "NOVEMBRE",
        "SYSMONTHS_TitleCaseGenitiveName": "Novembre",
        "SYSMONTHS_AbbreviatedName": "nov",
        "SYSMONTHS_LowerCaseAbbreviatedName": "nov",
        "SYSMONTHS_UpperCaseAbbreviatedName": "NOV",
        "SYSMONTHS_TitleCaseAbbreviatedName": "Nov",
        "SYSMONTHS_AbbreviatedGenitiveName": "nov",
        "SYSMONTHS_LowerCaseAbbreviatedGenitiveName": "nov",
        "SYSMONTHS_UpperCaseAbbreviatedGenitiveName": "NOV",
        "SYSMONTHS_TitleCaseAbbreviatedGenitiveName": "Nov"
    },
    {
        "SYSMONTHS_SYSLANG_LCID": 2064,
        "SYSMONTHS_MonthIndexBaseZero": 11,
        "SYSMONTHS_MonthIndexBaseOne": 12,
        "SYSMONTHS_SYSLANG_IetfLanguageTag": "it-CH",
        "SYSMONTHS_Name": "dicembre",
        "SYSMONTHS_LowerCaseName": "dicembre",
        "SYSMONTHS_UpperCaseName": "DICEMBRE",
        "SYSMONTHS_TitleCaseName": "Dicembre",
        "SYSMONTHS_GenitiveName": "dicembre",
        "SYSMONTHS_LowerCaseGenitiveName": "dicembre",
        "SYSMONTHS_UpperCaseGenitiveName": "DICEMBRE",
        "SYSMONTHS_TitleCaseGenitiveName": "Dicembre",
        "SYSMONTHS_AbbreviatedName": "dic",
        "SYSMONTHS_LowerCaseAbbreviatedName": "dic",
        "SYSMONTHS_UpperCaseAbbreviatedName": "DIC",
        "SYSMONTHS_TitleCaseAbbreviatedName": "Dic",
        "SYSMONTHS_AbbreviatedGenitiveName": "dic",
        "SYSMONTHS_LowerCaseAbbreviatedGenitiveName": "dic",
        "SYSMONTHS_UpperCaseAbbreviatedGenitiveName": "DIC",
        "SYSMONTHS_TitleCaseAbbreviatedGenitiveName": "Dic"
    },
    {
        "SYSMONTHS_SYSLANG_LCID": 4108,
        "SYSMONTHS_MonthIndexBaseZero": 0,
        "SYSMONTHS_MonthIndexBaseOne": 1,
        "SYSMONTHS_SYSLANG_IetfLanguageTag": "fr-CH",
        "SYSMONTHS_Name": "janvier",
        "SYSMONTHS_LowerCaseName": "janvier",
        "SYSMONTHS_UpperCaseName": "JANVIER",
        "SYSMONTHS_TitleCaseName": "Janvier",
        "SYSMONTHS_GenitiveName": "janvier",
        "SYSMONTHS_LowerCaseGenitiveName": "janvier",
        "SYSMONTHS_UpperCaseGenitiveName": "JANVIER",
        "SYSMONTHS_TitleCaseGenitiveName": "Janvier",
        "SYSMONTHS_AbbreviatedName": "janv.",
        "SYSMONTHS_LowerCaseAbbreviatedName": "janv.",
        "SYSMONTHS_UpperCaseAbbreviatedName": "JANV.",
        "SYSMONTHS_TitleCaseAbbreviatedName": "Janv.",
        "SYSMONTHS_AbbreviatedGenitiveName": "janv.",
        "SYSMONTHS_LowerCaseAbbreviatedGenitiveName": "janv.",
        "SYSMONTHS_UpperCaseAbbreviatedGenitiveName": "JANV.",
        "SYSMONTHS_TitleCaseAbbreviatedGenitiveName": "Janv."
    },
    {
        "SYSMONTHS_SYSLANG_LCID": 4108,
        "SYSMONTHS_MonthIndexBaseZero": 1,
        "SYSMONTHS_MonthIndexBaseOne": 2,
        "SYSMONTHS_SYSLANG_IetfLanguageTag": "fr-CH",
        "SYSMONTHS_Name": "février",
        "SYSMONTHS_LowerCaseName": "février",
        "SYSMONTHS_UpperCaseName": "FÉVRIER",
        "SYSMONTHS_TitleCaseName": "Février",
        "SYSMONTHS_GenitiveName": "février",
        "SYSMONTHS_LowerCaseGenitiveName": "février",
        "SYSMONTHS_UpperCaseGenitiveName": "FÉVRIER",
        "SYSMONTHS_TitleCaseGenitiveName": "Février",
        "SYSMONTHS_AbbreviatedName": "févr.",
        "SYSMONTHS_LowerCaseAbbreviatedName": "févr.",
        "SYSMONTHS_UpperCaseAbbreviatedName": "FÉVR.",
        "SYSMONTHS_TitleCaseAbbreviatedName": "Févr.",
        "SYSMONTHS_AbbreviatedGenitiveName": "févr.",
        "SYSMONTHS_LowerCaseAbbreviatedGenitiveName": "févr.",
        "SYSMONTHS_UpperCaseAbbreviatedGenitiveName": "FÉVR.",
        "SYSMONTHS_TitleCaseAbbreviatedGenitiveName": "Févr."
    },
    {
        "SYSMONTHS_SYSLANG_LCID": 4108,
        "SYSMONTHS_MonthIndexBaseZero": 2,
        "SYSMONTHS_MonthIndexBaseOne": 3,
        "SYSMONTHS_SYSLANG_IetfLanguageTag": "fr-CH",
        "SYSMONTHS_Name": "mars",
        "SYSMONTHS_LowerCaseName": "mars",
        "SYSMONTHS_UpperCaseName": "MARS",
        "SYSMONTHS_TitleCaseName": "Mars",
        "SYSMONTHS_GenitiveName": "mars",
        "SYSMONTHS_LowerCaseGenitiveName": "mars",
        "SYSMONTHS_UpperCaseGenitiveName": "MARS",
        "SYSMONTHS_TitleCaseGenitiveName": "Mars",
        "SYSMONTHS_AbbreviatedName": "mars",
        "SYSMONTHS_LowerCaseAbbreviatedName": "mars",
        "SYSMONTHS_UpperCaseAbbreviatedName": "MARS",
        "SYSMONTHS_TitleCaseAbbreviatedName": "Mars",
        "SYSMONTHS_AbbreviatedGenitiveName": "mars",
        "SYSMONTHS_LowerCaseAbbreviatedGenitiveName": "mars",
        "SYSMONTHS_UpperCaseAbbreviatedGenitiveName": "MARS",
        "SYSMONTHS_TitleCaseAbbreviatedGenitiveName": "Mars"
    },
    {
        "SYSMONTHS_SYSLANG_LCID": 4108,
        "SYSMONTHS_MonthIndexBaseZero": 3,
        "SYSMONTHS_MonthIndexBaseOne": 4,
        "SYSMONTHS_SYSLANG_IetfLanguageTag": "fr-CH",
        "SYSMONTHS_Name": "avril",
        "SYSMONTHS_LowerCaseName": "avril",
        "SYSMONTHS_UpperCaseName": "AVRIL",
        "SYSMONTHS_TitleCaseName": "Avril",
        "SYSMONTHS_GenitiveName": "avril",
        "SYSMONTHS_LowerCaseGenitiveName": "avril",
        "SYSMONTHS_UpperCaseGenitiveName": "AVRIL",
        "SYSMONTHS_TitleCaseGenitiveName": "Avril",
        "SYSMONTHS_AbbreviatedName": "avr.",
        "SYSMONTHS_LowerCaseAbbreviatedName": "avr.",
        "SYSMONTHS_UpperCaseAbbreviatedName": "AVR.",
        "SYSMONTHS_TitleCaseAbbreviatedName": "Avr.",
        "SYSMONTHS_AbbreviatedGenitiveName": "avr.",
        "SYSMONTHS_LowerCaseAbbreviatedGenitiveName": "avr.",
        "SYSMONTHS_UpperCaseAbbreviatedGenitiveName": "AVR.",
        "SYSMONTHS_TitleCaseAbbreviatedGenitiveName": "Avr."
    },
    {
        "SYSMONTHS_SYSLANG_LCID": 4108,
        "SYSMONTHS_MonthIndexBaseZero": 4,
        "SYSMONTHS_MonthIndexBaseOne": 5,
        "SYSMONTHS_SYSLANG_IetfLanguageTag": "fr-CH",
        "SYSMONTHS_Name": "mai",
        "SYSMONTHS_LowerCaseName": "mai",
        "SYSMONTHS_UpperCaseName": "MAI",
        "SYSMONTHS_TitleCaseName": "Mai",
        "SYSMONTHS_GenitiveName": "mai",
        "SYSMONTHS_LowerCaseGenitiveName": "mai",
        "SYSMONTHS_UpperCaseGenitiveName": "MAI",
        "SYSMONTHS_TitleCaseGenitiveName": "Mai",
        "SYSMONTHS_AbbreviatedName": "mai",
        "SYSMONTHS_LowerCaseAbbreviatedName": "mai",
        "SYSMONTHS_UpperCaseAbbreviatedName": "MAI",
        "SYSMONTHS_TitleCaseAbbreviatedName": "Mai",
        "SYSMONTHS_AbbreviatedGenitiveName": "mai",
        "SYSMONTHS_LowerCaseAbbreviatedGenitiveName": "mai",
        "SYSMONTHS_UpperCaseAbbreviatedGenitiveName": "MAI",
        "SYSMONTHS_TitleCaseAbbreviatedGenitiveName": "Mai"
    },
    {
        "SYSMONTHS_SYSLANG_LCID": 4108,
        "SYSMONTHS_MonthIndexBaseZero": 5,
        "SYSMONTHS_MonthIndexBaseOne": 6,
        "SYSMONTHS_SYSLANG_IetfLanguageTag": "fr-CH",
        "SYSMONTHS_Name": "juin",
        "SYSMONTHS_LowerCaseName": "juin",
        "SYSMONTHS_UpperCaseName": "JUIN",
        "SYSMONTHS_TitleCaseName": "Juin",
        "SYSMONTHS_GenitiveName": "juin",
        "SYSMONTHS_LowerCaseGenitiveName": "juin",
        "SYSMONTHS_UpperCaseGenitiveName": "JUIN",
        "SYSMONTHS_TitleCaseGenitiveName": "Juin",
        "SYSMONTHS_AbbreviatedName": "juin",
        "SYSMONTHS_LowerCaseAbbreviatedName": "juin",
        "SYSMONTHS_UpperCaseAbbreviatedName": "JUIN",
        "SYSMONTHS_TitleCaseAbbreviatedName": "Juin",
        "SYSMONTHS_AbbreviatedGenitiveName": "juin",
        "SYSMONTHS_LowerCaseAbbreviatedGenitiveName": "juin",
        "SYSMONTHS_UpperCaseAbbreviatedGenitiveName": "JUIN",
        "SYSMONTHS_TitleCaseAbbreviatedGenitiveName": "Juin"
    },
    {
        "SYSMONTHS_SYSLANG_LCID": 4108,
        "SYSMONTHS_MonthIndexBaseZero": 6,
        "SYSMONTHS_MonthIndexBaseOne": 7,
        "SYSMONTHS_SYSLANG_IetfLanguageTag": "fr-CH",
        "SYSMONTHS_Name": "juillet",
        "SYSMONTHS_LowerCaseName": "juillet",
        "SYSMONTHS_UpperCaseName": "JUILLET",
        "SYSMONTHS_TitleCaseName": "Juillet",
        "SYSMONTHS_GenitiveName": "juillet",
        "SYSMONTHS_LowerCaseGenitiveName": "juillet",
        "SYSMONTHS_UpperCaseGenitiveName": "JUILLET",
        "SYSMONTHS_TitleCaseGenitiveName": "Juillet",
        "SYSMONTHS_AbbreviatedName": "juil.",
        "SYSMONTHS_LowerCaseAbbreviatedName": "juil.",
        "SYSMONTHS_UpperCaseAbbreviatedName": "JUIL.",
        "SYSMONTHS_TitleCaseAbbreviatedName": "Juil.",
        "SYSMONTHS_AbbreviatedGenitiveName": "juil.",
        "SYSMONTHS_LowerCaseAbbreviatedGenitiveName": "juil.",
        "SYSMONTHS_UpperCaseAbbreviatedGenitiveName": "JUIL.",
        "SYSMONTHS_TitleCaseAbbreviatedGenitiveName": "Juil."
    },
    {
        "SYSMONTHS_SYSLANG_LCID": 4108,
        "SYSMONTHS_MonthIndexBaseZero": 7,
        "SYSMONTHS_MonthIndexBaseOne": 8,
        "SYSMONTHS_SYSLANG_IetfLanguageTag": "fr-CH",
        "SYSMONTHS_Name": "août",
        "SYSMONTHS_LowerCaseName": "août",
        "SYSMONTHS_UpperCaseName": "AOÛT",
        "SYSMONTHS_TitleCaseName": "Août",
        "SYSMONTHS_GenitiveName": "août",
        "SYSMONTHS_LowerCaseGenitiveName": "août",
        "SYSMONTHS_UpperCaseGenitiveName": "AOÛT",
        "SYSMONTHS_TitleCaseGenitiveName": "Août",
        "SYSMONTHS_AbbreviatedName": "août",
        "SYSMONTHS_LowerCaseAbbreviatedName": "août",
        "SYSMONTHS_UpperCaseAbbreviatedName": "AOÛT",
        "SYSMONTHS_TitleCaseAbbreviatedName": "Août",
        "SYSMONTHS_AbbreviatedGenitiveName": "août",
        "SYSMONTHS_LowerCaseAbbreviatedGenitiveName": "août",
        "SYSMONTHS_UpperCaseAbbreviatedGenitiveName": "AOÛT",
        "SYSMONTHS_TitleCaseAbbreviatedGenitiveName": "Août"
    },
    {
        "SYSMONTHS_SYSLANG_LCID": 4108,
        "SYSMONTHS_MonthIndexBaseZero": 8,
        "SYSMONTHS_MonthIndexBaseOne": 9,
        "SYSMONTHS_SYSLANG_IetfLanguageTag": "fr-CH",
        "SYSMONTHS_Name": "septembre",
        "SYSMONTHS_LowerCaseName": "septembre",
        "SYSMONTHS_UpperCaseName": "SEPTEMBRE",
        "SYSMONTHS_TitleCaseName": "Septembre",
        "SYSMONTHS_GenitiveName": "septembre",
        "SYSMONTHS_LowerCaseGenitiveName": "septembre",
        "SYSMONTHS_UpperCaseGenitiveName": "SEPTEMBRE",
        "SYSMONTHS_TitleCaseGenitiveName": "Septembre",
        "SYSMONTHS_AbbreviatedName": "sept.",
        "SYSMONTHS_LowerCaseAbbreviatedName": "sept.",
        "SYSMONTHS_UpperCaseAbbreviatedName": "SEPT.",
        "SYSMONTHS_TitleCaseAbbreviatedName": "Sept.",
        "SYSMONTHS_AbbreviatedGenitiveName": "sept.",
        "SYSMONTHS_LowerCaseAbbreviatedGenitiveName": "sept.",
        "SYSMONTHS_UpperCaseAbbreviatedGenitiveName": "SEPT.",
        "SYSMONTHS_TitleCaseAbbreviatedGenitiveName": "Sept."
    },
    {
        "SYSMONTHS_SYSLANG_LCID": 4108,
        "SYSMONTHS_MonthIndexBaseZero": 9,
        "SYSMONTHS_MonthIndexBaseOne": 10,
        "SYSMONTHS_SYSLANG_IetfLanguageTag": "fr-CH",
        "SYSMONTHS_Name": "octobre",
        "SYSMONTHS_LowerCaseName": "octobre",
        "SYSMONTHS_UpperCaseName": "OCTOBRE",
        "SYSMONTHS_TitleCaseName": "Octobre",
        "SYSMONTHS_GenitiveName": "octobre",
        "SYSMONTHS_LowerCaseGenitiveName": "octobre",
        "SYSMONTHS_UpperCaseGenitiveName": "OCTOBRE",
        "SYSMONTHS_TitleCaseGenitiveName": "Octobre",
        "SYSMONTHS_AbbreviatedName": "oct.",
        "SYSMONTHS_LowerCaseAbbreviatedName": "oct.",
        "SYSMONTHS_UpperCaseAbbreviatedName": "OCT.",
        "SYSMONTHS_TitleCaseAbbreviatedName": "Oct.",
        "SYSMONTHS_AbbreviatedGenitiveName": "oct.",
        "SYSMONTHS_LowerCaseAbbreviatedGenitiveName": "oct.",
        "SYSMONTHS_UpperCaseAbbreviatedGenitiveName": "OCT.",
        "SYSMONTHS_TitleCaseAbbreviatedGenitiveName": "Oct."
    },
    {
        "SYSMONTHS_SYSLANG_LCID": 4108,
        "SYSMONTHS_MonthIndexBaseZero": 10,
        "SYSMONTHS_MonthIndexBaseOne": 11,
        "SYSMONTHS_SYSLANG_IetfLanguageTag": "fr-CH",
        "SYSMONTHS_Name": "novembre",
        "SYSMONTHS_LowerCaseName": "novembre",
        "SYSMONTHS_UpperCaseName": "NOVEMBRE",
        "SYSMONTHS_TitleCaseName": "Novembre",
        "SYSMONTHS_GenitiveName": "novembre",
        "SYSMONTHS_LowerCaseGenitiveName": "novembre",
        "SYSMONTHS_UpperCaseGenitiveName": "NOVEMBRE",
        "SYSMONTHS_TitleCaseGenitiveName": "Novembre",
        "SYSMONTHS_AbbreviatedName": "nov.",
        "SYSMONTHS_LowerCaseAbbreviatedName": "nov.",
        "SYSMONTHS_UpperCaseAbbreviatedName": "NOV.",
        "SYSMONTHS_TitleCaseAbbreviatedName": "Nov.",
        "SYSMONTHS_AbbreviatedGenitiveName": "nov.",
        "SYSMONTHS_LowerCaseAbbreviatedGenitiveName": "nov.",
        "SYSMONTHS_UpperCaseAbbreviatedGenitiveName": "NOV.",
        "SYSMONTHS_TitleCaseAbbreviatedGenitiveName": "Nov."
    },
    {
        "SYSMONTHS_SYSLANG_LCID": 4108,
        "SYSMONTHS_MonthIndexBaseZero": 11,
        "SYSMONTHS_MonthIndexBaseOne": 12,
        "SYSMONTHS_SYSLANG_IetfLanguageTag": "fr-CH",
        "SYSMONTHS_Name": "décembre",
        "SYSMONTHS_LowerCaseName": "décembre",
        "SYSMONTHS_UpperCaseName": "DÉCEMBRE",
        "SYSMONTHS_TitleCaseName": "Décembre",
        "SYSMONTHS_GenitiveName": "décembre",
        "SYSMONTHS_LowerCaseGenitiveName": "décembre",
        "SYSMONTHS_UpperCaseGenitiveName": "DÉCEMBRE",
        "SYSMONTHS_TitleCaseGenitiveName": "Décembre",
        "SYSMONTHS_AbbreviatedName": "déc.",
        "SYSMONTHS_LowerCaseAbbreviatedName": "déc.",
        "SYSMONTHS_UpperCaseAbbreviatedName": "DÉC.",
        "SYSMONTHS_TitleCaseAbbreviatedName": "Déc.",
        "SYSMONTHS_AbbreviatedGenitiveName": "déc.",
        "SYSMONTHS_LowerCaseAbbreviatedGenitiveName": "déc.",
        "SYSMONTHS_UpperCaseAbbreviatedGenitiveName": "DÉC.",
        "SYSMONTHS_TitleCaseAbbreviatedGenitiveName": "Déc."
    }
];
