
;WITH CTE AS 
(
	SELECT FT_De, T_FMS_Navigation.* FROM T_FMS_Navigation 
	LEFT JOIN T_FMS_Translation ON FT_UID = NA_FT_UID 
	WHERE NA_UID = '6E50D12C-9E29-419E-B82F-F1040727485B'
)
-- SELECT  * FROM CTE 
UPDATE CTE SET NA_MOD_UID = (SELECT TOP 1 MOD_UID FROM T_SYS_Module WHERE MOD_Code = 'M-70') 
